version: '2.1'

services:
  curso-angular:
    image: curso-angular
    build: .
    ports:
      - 8081:80

# docker compose up roda o arquivo que constroi e executa a imagem (criada manual no dockerfile)
# ctrl+shift+p docker compose up